apiVersion: v1
kind: Pod
metadata:
  name: clash-proxy
spec:
  template:
    metadata:
      labels:
        app: clash
  containers:
    - name: clash-proxy
      image: clash-proxy:latest
      imagePullPolicy: Never # k8s不能直接使用本地镜像, 解决方案: https://medium.com/swlh/how-to-run-locally-built-docker-images-in-kubernetes-b28fbc32cc1d
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
